name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Your Code
        uses: actions/checkout@v2
      - name: Create file "hello.txt" with the word Hello
        run: echo "Hello" > hello.txt
      - name: Say Hello to the World
        run: echo "Hello, World!"
